name: Fly Deploy
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # 定时任务
    - cron: "0 0 * * *" # 每天 0 点跑 => 东八区 8点

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Build frontend
        run: yarn build
        
      - name: Deploy app
        run:  mv fly.toml ./dist && cd dist && flyctl deploy --remote-only
